on:
  workflow_call:
    inputs:
      assembly_name:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      api_key:
        required: true

jobs:
  Stable:
    runs-on: ubuntu-latest
    environment: Release
    steps:
    - name: Download Signed Packages
      uses: actions/download-artifact@v2
      with:
        name: signed
        path: signed

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Push Stable Package
      run: |
        nuget push signed/stable/${{inputs.assembly_name}}.${{inputs.version}}.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.api_key }} -Verbosity detailed -NonInteractive
